FROM node:22.2.0-alpine AS builder
WORKDIR /app/builder
COPY package.json ./
RUN yarn config set registry http://81.200.146.252:4873
RUN yarn config set network-timeout 600000  # Установка таймаута сети на 10 минут
RUN yarn config set child-concurrency 10  # Установка параллельности процессов
RUN yarn

